# Generated by Django 5.2.7 on 2025-10-17 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('age', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16)], verbose_name='возраст')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10, verbose_name='пол')),
                ('active', models.BooleanField(verbose_name='активный')),
            ],
        ),
    ]
