# Generated by Django 5.2.7 on 2025-10-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('py', 'python'), ('c', 'C++'), ('js', 'JavaScript')], max_length=15, verbose_name='курсы')),
                ('start_date', models.DateField(verbose_name='начало курса')),
                ('end_date', models.DateField(verbose_name='конец курса')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(default=0, verbose_name='оценка')),
                ('date', models.DateField(verbose_name='дата')),
            ],
            options={
                'verbose_name': 'оценки',
                'verbose_name_plural': 'оценка',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname'], 'verbose_name': 'студенты', 'verbose_name_plural': 'студенты'},
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, to='students.courses', verbose_name='курсы'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['surname'], name='students_st_surname_0e1b31_idx'),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.courses', verbose_name='курсы'),
        ),
        migrations.AddField(
            model_name='grade',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='чья оценка'),
        ),
    ]
